server:
  contextPath: /app
  port: ${port:8081}

management:
  contextPath: /admin
  port: ${port:8081}

# Default Spring profile
spring:
  profiles:
    active: dev

# Set default password for management URLs. Not used as it's overridden by Spring Security configuration.
security:
  user:
    password: password
